development:
  adapter: mysql2
  database: <%= ENV['DATABASE_NAME'] || 'sinatra_ruby' %>
  host: <%= ENV['DATABASE_HOST'] || '127.0.0.1' %>
  port: <%= ENV['DATABASE_PORT'] || '3306' %>
  username: <%= ENV['DATABASE_USERNAME'] || 'root' %>
  password: <%= ENV['DATABASE_PASSWORD'] || '1' %>